public class PuzzleJavaTest{
    public static void main(String[] args){
        PuzzleJava puzzlejava = new PuzzleJava();
        // gets 10 random numbers between 1 and 20
            // System.out.println(puzzlejava.getTenRolls());

        //gets random character
            // System.out.println(puzzlejava.getRandomLetter());

        //generates 8 character string
            System.out.println(puzzlejava.generatePassword());
        
    }
}